#!/bin/bash
# Establishes a common CLI base for all systems
# Install all dotfiles into the home directory
#
# Strap (prep, basic deps, install homebrew) -> <this script> -> Strap (brew bundle) -> dotfiles/script/strap-after-setup -> dotfiles/bin/update-host

# Install our deps
if [ "$(uname -s)" == "Darwin" ]
then
  if [[ -x "$(command -v brew)" ]]
  then
    brew install stow
  else
    echo "Can't find homebrew"
    exit 1
  fi
else
  DISTRO="$(lsb_release -is)"
  if [ "$DISTRO" == "Ubuntu" ] || [ "$DISTRO" == "Debian" ]
  then
    sudo apt-get -y install stow zsh openssh-server

    # Remove snap
    # $HOME/.dotfiles/script/remove-snap

    # Install flakpak
    sudo apt install flatpak gnome-software gnome-software-plugin-flatpak -y
    sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    # Install desktop apps
    $HOME/.dotfiles/script/ubuntu-install-1password
    $HOME/.dotfiles/script/ubuntu-install-rustdesk
    $HOME/.dotfiles/script/ubuntu-install-syncthing

  elif [ "$DISTRO" == "RedHat" ] || [ "$DISTRO" == "RHEL" ] || [ "$DISTRO" == "CentOS" ]
  then
    sudo yum -y install stow
  elif [ "$DISTRO" == "Fedora" ]
  then
    sudo dnf -y install stow
  elif [ "$DISTRO" == "Arch" ] || [ "$DISTRO" == "ManjaroLinux" ]
  then
    sudo pacman -Sy --noconfirm --needed stow
  else
    echo "Unknown/unsupported Linux distro"
    exit 1
  fi
fi

if [ -x "$HOME/.dotfiles/bin/.bin/stow.sh" ]
then
  "$HOME/.dotfiles/bin/.bin/stow.sh"
else
  echo "Stow setup is missing"
fi

# Change our shell to ZSH
ZSH=`which zsh`
if [ -n "$ZSH" ]
then
  if [ "$0" != "$ZSH" ]
  then
    sudo chsh -s "$ZSH" "$USER"
    logk
  fi
fi

if [ -n "$CODESPACES" ]; then
  # Fix up Codespaces permissions
  chmod 700 /workspaces

  # Don't try to git gc github/github, it happens often and takes ages
  if [ "$CODESPACE_VSCODE_FOLDER" = "/workspaces/github" ]; then
    git -C /workspaces/github config gc.auto 0
  fi
fi
