#!/bin/bash

[ "$USER" = "root" ] && echo "Run as yourself, not root." && exit 1

OWNER=rustdesk
REPO=rustdesk
PACKAGE=rustdesk
source /etc/os-release
ARCH=$(dpkg --print-architecture)

if [ $ARCH == "amd64" ]
then
   ARCH="x86_64"
else
   echo "This install script is not compatible with $ARCH."
   exit 1
fi

# E.g. https://github.com/rustdesk/rustdesk/releases/download/1.4.5/rustdesk-1.4.5-x86_64.deb

case "$ID" in
   ubuntu)
      if [[ "$VERSION_ID" =~ ^(25.10|24.04)$ ]]
      then
         SUFFIX="${ARCH}"
      else
         echo "This installer is not compatible with Ubuntu $VERSION_ID"
         exit 1
      fi
      ;;
   *)
      echo "This install script is not compatible with $ID."
      exit 1
      ;;
esac

DEB_URL=$(
   curl -s "https://api.github.com/repos/${OWNER}/${REPO}/releases/latest" | \
   grep -oP "https://github.com/${OWNER}/${REPO}/releases/download/[^\s/]+/${PACKAGE}-[^\s/-]+-${SUFFIX}.deb"
)
if [[ -z "$DEB_URL" ]]
then
   echo "Error: Failed to retrieve the .deb package URL from GitHub."
   exit 1
fi
DEB_FILE=$(basename $DEB_URL)
DEB_FILEPATH=$(mktemp -t XXXXXXX.${DEB_FILE})

echo "Downloading ${DEB_FILE}..."
curl -Ls -o $DEB_FILEPATH $DEB_URL

echo "Installing ${DEB_FILE}..."
sudo apt install -q -yf $DEB_FILEPATH
rm $DEB_FILEPATH

exit 0
