#!/bin/bash

[ "$USER" = "root" ] && echo "Run as yourself, not root." && exit 1

# Note: can't use deb822 because the package installs its own keyring/apt source files

# Fetch keyring
sudo rm -f /usr/share/keyrings/1password-archive-keyring.gpg
curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg

# Create deb source
echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main' | sudo tee /etc/apt/sources.list.d/1password.list >/dev/null

# Update apt
sudo apt -q update

# Install
sudo apt install -y 1password 1password-cli

# Create systemd service
cat <<EOF | sudo tee /usr/lib/systemd/user/1password.service >/dev/null
[Unit]
Description=1Password
Requires=graphical-session.target
After=graphical-session.target

[Service]
ExecStart=/usr/bin/1password --silent
Type=exec
TimeoutSec=60

[Install]
Alias=1password.service
WantedBy=graphical-session.target
EOF
sudo systemctl daemon-reload

# Start service
systemctl --user enable 1password
systemctl --user start 1password

exit 0
